#!/bin/bash
set -e

cargo build --release --features generate --locked --target-dir target
scripts/mkmo locale/
strip target/release/pwa

tar --zstd -cf pwa.tar.zst man completions paru.conf locale -C target/release pwa

